### ISSUE TITLE
The image pull link of pyslam_cuda is invalid

### ISSUE THREAD

**Issue by sqn175** [luigifreda/rosdocker#10]
Hi, luigifreda, the pyslam_cuda docker image link is invalid in readme. Is there any already built image in DockerHub? Thanks!

**Comment by luigifreda** [comment]
Hi, 
Thanks for your feedback. From the provided link you can access the docker images
https://github.com/luigifreda/rosdocker/pkgs/container/rosdocker


![Image](https://github.com/user-attachments/assets/f95c7fde-faf9-4387-ba28-01caf9a75518)

**Comment by sqn175** [comment]
Hi, 
Thanks for your reply. The link is still **not** accessible. Is there any permission issue? I see a `Private` tag in your provided picture.  ![Image](https://github.com/user-attachments/assets/4d69e0ea-5b1d-47e1-abc6-f11bb95fb9a6)

**Comment by luigifreda** [comment]
Should be solved now

**Comment by sqn175** [comment]
It works now, thank you!

**Comment by sqn175** [comment]
Hi, luigifreda,
The image may be incomplete. Pulling the image gives a `unexpected EOF` error. 
```shell
pyslam_cuda: Pulling from luigifreda/rosdocker
7a2c55901189: Already exists 
755e535b54a3: Already exists 
24ff69e0a1e4: Already exists 
76a627ca5e65: Already exists 
35817692a87e: Already exists 
84b6a42e847a: Already exists 
4639b7cd68e5: Already exists 
a7bc10701a5b: Already exists 
7d32a9230f8f: Already exists 
8c35a1861813: Already exists 
e3f63d7242f5: Already exists 
cf771ecfa045: Pull complete 
cf305ce249df: Pull complete 
36a4bb00f667: Pull complete 
a1516f2aa8fe: Pull complete 
98412f306e25: Pull complete 
8834252af425: Pull complete 
27413b79094b: Pull complete 
5181a8dfd792: Pull complete 
47774bb8484f: Pull complete 
56550eec8a69: Pull complete 
824e63aa5670: Pull complete 
4e83a0bef959: Pull complete 
db766539330c: Pull complete 
c8729eda7e06: Pull complete 
f3101b6d291b: Pull complete 
dee9f2a21957: Pull complete 
a045080643c8: Pull complete 
5ce220195582: Pull complete 
3a5483556028: Pull complete 
dae5c79e649b: Pull complete 
5e8b62b48083: Pull complete 
14911b9c340a: Pull complete 
b236cb4fc224: Pull complete 
eb33ab9e11e1: Pull complete 
4f4fb700ef54: Pull complete 
e7883248995b: Pull complete 
fd869e8b39a5: Pull complete 
6d4826249cb2: Downloading [==================================================>]  8.929GB/8.929GB
fea0c05d312c: Download complete 
40bc71861a55: Download complete 
unexpected EOF
```

**Comment by luigifreda** [comment]
Thanks for the feedback. Working on that. Out of curiosity, did you try to directly build the docker image?

**Comment by sqn175** [comment]
Hi, luigifreda. Already tried to build the docker image, but failed several times due to internet connection issue since i'm in China mainland. I also tried to directly build pyslam_cuda natively, but still failed due to the same internet issue.
